# Generated by Django 6.0.2 on 2026-03-07 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription_time',
            field=models.DurationField(default=datetime.timedelta(days=12, seconds=45040)),
        ),
    ]
