# Generated by Django 6.0.2 on 2026-03-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_subscription_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='url',
            field=models.URLField(default='https://adel.com'),
        ),
    ]
