# Generated by Django 6.0.2 on 2026-03-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subscription_time',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='url',
        ),
    ]
