# Generated by Django 6.0.2 on 2026-03-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_profile_subscription_time_remove_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='binary',
            field=models.BinaryField(null=True),
        ),
    ]
