# Generated by Django 6.0.2 on 2026-03-08 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_profile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='binary',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='file',
        ),
    ]
