# Generated by Django 6.0.2 on 2026-03-08 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='descriptions',
            new_name='description',
        ),
    ]
