# Generated by Django 6.0.2 on 2026-03-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='post_image',
            field=models.ImageField(null=True, upload_to='images/articles'),
        ),
    ]
