# Generated by Django 6.0.2 on 2026-03-19 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_article_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='banner_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='article',
            name='post_image',
        ),
    ]
