# Generated by Django 6.0.2 on 2026-03-28 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='slug',
            new_name='my_slug',
        ),
    ]
