# Generated by Django 6.0.2 on 2026-03-28 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_rename_slug_article_my_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='my_slug',
            new_name='slug',
        ),
    ]
