# Generated by Django 6.0.2 on 2026-03-29 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_rename_my_slug_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 29, 4, 49, 12, 628868, tzinfo=datetime.timezone.utc)),
        ),
    ]
